### ISSUE TITLE
Error al generar tickets con títulos con palabras muy largas

### ISSUE THREAD

**Issue by aeburriel** [aeburriel/uji-par#2]
El título "SKIZOPHONIC-ELS MONIATOS" provoca la siguiente excepción:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911) ~[na:1.7.0_111]
	at es.uji.apps.par.report.BenicassimBaseReport.getTituloPequenyoAMostrar(BenicassimBaseReport.java:31) ~[uji-par-reports-benicassim-0.0.1-SNAPSHOT.jar:na]
	at es.uji.apps.par.report.EntradaTaquillaReport.createEntradaDerecha(EntradaTaquillaReport.java:149) ~[uji-par-reports-benicassim-0.0.1-SNAPSHOT.jar:na]
	at es.uji.apps.par.report.EntradaTaquillaReport.creaSeccionEntrada(EntradaTaquillaReport.java:123) ~[uji-par-reports-benicassim-0.0.1-SNAPSHOT.jar:na]
	at es.uji.apps.par.report.EntradaTaquillaReport.generaPaginaButaca(EntradaTaquillaReport.java:76) ~[uji-par-reports-benicassim-0.0.1-SNAPSHOT.jar:na]
	at es.uji.apps.par.services.EntradasService.rellenaEntradaTaquilla(EntradasService.java:128) ~[uji-par-base-0.0.12-SNAPSHOT.jar:na]
	at es.uji.apps.par.services.EntradasService.generaEntradaTaquilla(EntradasService.java:74) ~[uji-par-base-0.0.12-SNAPSHOT.jar:na]
	at es.uji.apps.par.services.rest.CompraResource.generaEntradaTaquilla(CompraResource.java:307) ~[CompraResource.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_111]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_111]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511) [jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442) [jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391) [jersey-server-1.17.jar:1.17]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381) [jersey-server-1.17.jar:1.17]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.17.jar:1.17]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.17.jar:1.17]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.17.jar:1.17]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat-servlet-api-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.56.jar:7.0.56]
	at es.uji.apps.par.auth.AuthFilter.doFilter(AuthFilter.java:66) [AuthFilter.class:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190) [tomcat-coyote-7.0.56.jar:7.0.56]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote-7.0.56.jar:7.0.56]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote-7.0.56.jar:7.0.56]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote-7.0.56.jar:7.0.56]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_111]
```
El problema está en el método _getTituloPequenyoAMostrar()_ de **BenicassimBaseReport.java**.
Tenemos el mismo problema en el método _getTextoRecortadoMostrar()_
Si no se consigue encontrar un espacio apopiado para cortar la cadena (_substring()_ devuelve índice negativo), hay que buscar otro punto de corte cualquiera. Sería interesante buscar por un conjunto de caracteres (espcio, coma, punto, punto y  coma, guión, ...)

**Comment by aeburriel** [comment]
Arreglado en 9c162351fb733c4e7911eb89cb70ac9da95531a2
